---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: solr-operator
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: Apache_Solr
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
